etcd config: handle decode err,  defaultkv option to avoid Read() err
go-micro/plugins pull request #71
Opened 2022-10-06 14:03 UTC by keepstep

1. ignore decode err in watch 
2. put /${prefix}/default "{}" to avoid Read() err

2022-10-06 15:03 UTC, Davincible requested changes

2022-10-07 03:41 UTC, keepstep commented on v4/config/source/etcd/etcd.go
> +	defaultKv bool
have resolved

2022-10-07 03:41 UTC, keepstep commented on v4/config/source/etcd/util.go
> +	var err error = nil
have resolved

2022-10-07 03:41 UTC, keepstep commented on v4/config/source/etcd/util.go
> +	var err error = nil
have resolved

2022-10-07 03:42 UTC, keepstep commented
Yes , I Have tested this also locally and make sure everything works correctly.

2022-10-07 03:46 UTC, Davincible approved these changes

2022-10-07 03:47 UTC, merged